// <auto-generated />
namespace IkeCode.Clinike.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V1_0_0_AddColumn_Roles_Title : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V1_0_0_AddColumn_Roles_Title));
        
        string IMigrationMetadata.Id
        {
            get { return "201510122350373_V1_0_0_AddColumn_Roles_Title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
