// <auto-generated />
namespace IkeCode.Clinike.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v1_0_0_CreateTable_Schedule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1_0_0_CreateTable_Schedule));
        
        string IMigrationMetadata.Id
        {
            get { return "201511281454175_v1_0_0_CreateTable_Schedule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
