// <auto-generated />
namespace IkeCode.Clinike.Person.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V100_AddPhoneTypeToPhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V100_AddPhoneTypeToPhone));
        
        string IMigrationMetadata.Id
        {
            get { return "201603291503571_V100_AddPhoneTypeToPhone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
